obj-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI) += chipone_tddi_v2_mmi.o

ccflags-y += -Wall
ccflags-y += -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/include \
             -I$(ANDROID_BUILD_TOP)/motorola/kernel/modules/drivers/input/touchscreen/chipone_tddi_v2_mmi

ccflags-$(CONFIG_INPUT_CHIPONE_0FLASH_MMI_NOTIFY_TOUCH_STATE) += -DCHIPONE_SET_TOUCH_STATE
ccflags-$(CONFIG_INPUT_CHIPONE_PANEL_NOTIFICATIONS) += -DCHIPONE_CONFIG_PANEL_NOTIFICATIONS
ccflags-$(CONFIG_BOARD_USES_DOUBLE_TAP_CTRL) += -DCONFIG_BOARD_USES_DOUBLE_TAP_CTRL
ccflags-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += -DCONFIG_INPUT_TOUCHSCREEN_MMI

ccflags-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_ESD) += -DCONFIG_CTS_ESD_PROTECTION
ccflags-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_ENABLE_DOUBLE_TAP) += -DCHIPONE_SENSOR_EN
ccflags-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_GTP_LAST_TIME) += -DCONFIG_GTP_LAST_TIME
ccflags-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_STOWED_MODE_EN) += -DCTS_STOWED_MODE_EN
ccflags-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_PM_BRL_SPI) += -DTOUCHSCREEN_PM_BRL_SPI
ccflags-$(CONFIG_TOUCHSCREEN_CHIPONE_V2_MMI_CHECK_DEVICE_BOOTMODE) += -DCTS_CHECK_DEVICE_BOOTMODE

ifeq ($(TARGET_BUILD_VARIANT),user)
    ccflags-y += -DCFG_CTS_FOR_GKI
endif

chipone_tddi_v2_mmi-objs := cts_driver.o
chipone_tddi_v2_mmi-objs += cts_core.o
chipone_tddi_v2_mmi-objs += cts_sfctrlv2.o
chipone_tddi_v2_mmi-objs += cts_spi_flash.o
chipone_tddi_v2_mmi-objs += cts_firmware.o
chipone_tddi_v2_mmi-objs += cts_test.o
chipone_tddi_v2_mmi-objs += cts_charger_detect.o
chipone_tddi_v2_mmi-objs += cts_earjack_detect.o
chipone_tddi_v2_mmi-objs += cts_tcs.o
chipone_tddi_v2_mmi-objs += cts_platform.o
chipone_tddi_v2_mmi-objs += cts_tool.o
chipone_tddi_v2_mmi-objs += cts_sysfs.o
chipone_tddi_v2_mmi-objs += cts_strerror.o
chipone_tddi_v2_mmi-objs += cts_oem.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../touchscreen_mmi/$(GKI_OBJ_MODULE_DIR)/Module.symvers
KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../../mmi_info/$(GKI_OBJ_MODULE_DIR)/Module.symvers
